export enum CurrencyCode {
    AUD = "AUD",
    BRL = "BRL",
    CAD = "CAD",
    CLP = "CLP",
    CNH = "CNH",
    CNY = "CNY",
    CZK = "CZK",
    DKK = "DKK",
    EUR = "EUR",
    HKD = "HKD",
    HUF = "HUF",
    ILS = "ILS",
    JPY = "JPY",
    KRW = "KRW",
    MXR = "MXR",
    MXN = "MXN",
    MYR = "MYR",
    NOK = "NOK",
    NZD = "NZD",
    PHP = "PHP",
    PLN = "PLN",
    GBP = "GBP",
    SGD = "SGD",
    SEK = "SEK",
    CHF = "CHF",
    TWD = "TWD",
    THB = "THB",
    TRY = "TRY",
    USD = "USD",
    ZAR = "ZAR",
}

export enum RegCode {
    INVALID = "",
    COMBINED = "00",
    REGULATED = "01",
    NON_SECURED = "02",
    SECURED = "03",
}

