name: Sanity check
on: push

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install 
        run: composer install 
      - name: Installing packages
        run: npm install
      - name: Running linter 
        run: npm run lint
      - name: Compiling
        run: npm run build

