name: Sanity check
on: push

jobs:
  sanity-check:
    name: Sanity Check
    runs-on: ubuntu-latest
    container:
      image: node:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Installing packages
        run: npm install
      - name: Running linter 
        run: npm run lint
      - name: Compiling
        run: npm run build

